# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ef4218461112c8de128e30a736921dac06661b380380386222eeb912e6879a68ccc05ba9c0fb9534ea1af2ece17283668d2ef1b673c75ac6dac382c4bfdd66a1

test:
  secret_key_base: a95f04c014708fecd6cf2d402f9ac8480953d4f6494f075258ec3b918c4885703073be0e5c4479107f412659c8080734be16f2fac822289bf12ac84c26227875

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
