# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c30036ba1337872dae1d3e26a5d6d319306893df8f3cf2eab0a22b4adfa39d0dc824649be30c3c94857b0187c1020a926f616b8bca4bc2e90a3d0ea7eda0c20a

test:
  secret_key_base: f35fd09cb0ef8c33bf78c293253e16ae3b7264d589745adad54e9d39c7f166870628f77b6ecb0daad32ff925cf0c4960cfd960e58e225f9af307be3c2bcde65b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
